### ISSUE TITLE
No error when UVC name is missing and download button is pushed

### ISSUE THREAD

**Issue by tudortimi** [uvmgen/issues#4]
**Describe the bug**
If the 'UVC name' is missing in section 1, clicking on the 'Download' button in section 8 will generate a file called '.zip' that only contains 'LICENSE'.

**Expected behavior**
I would expect an error message. Initially I thought it's because I didn't fill out other sections of the page (where no 'checkmark' symbols where shown).

**Comment by bdiz** [comment]
Download button is now disabled until all required data, including `UVC name`, has been collected from the user. Thank you!
